Recorded ADR for brille/X vs X/brille
pace-neutrons/pace-developers pull request #20
Opened 2020-11-29 15:51 UTC by mducle

Record decision reached at a meeting in October for calculators `X` to call `brille` for interpolation rather than reverse, and for these integration code to be in the calculator `X` rather than in `brille` or a third project.

2020-11-30 13:08 UTC, cmarooney-stfc commented on documentation/adr/0009-brille-integration.md
> +
Only comment here is that the text says that euphonic and spinw compute quantities in reciprocal space to make those quantities user friendly. I think you mean that the interpolation functionality should be integrated with the codes to make them or it more user friendly.

2020-12-01 09:51 UTC, rebeccafair approved these changes
Looks good to me!

2020-12-01 10:02 UTC, g5t requested changes
Other than not wanting to limit the scope of `brillem` this all looks good.

2020-12-01 10:02 UTC, g5t commented on documentation/adr/0009-brille-integration.md
> +leaving a minimal `brillem` for Matlab users to access the symmetry operations functionality of `brille`.
```suggestion
leaving a minimal `brillem` for Matlab users to access the functionality of `brille`.
```
I thought we agreed that `brillem` should still contain a bare-bones interface to the `brille` 'grids' and their linear interpolation routines.

2020-12-01 10:20 UTC, merged